version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/add-on-reports-generator"
    schedule:
      interval: "weekly"
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
